-- 코드를 입력하세요
SELECT FO.PRODUCT_ID,	FP.PRODUCT_NAME,	sum(AMOUNT)*FP.PRICE as TOTAL_SALES
FROM FOOD_ORDER FO join FOOD_PRODUCT FP on FO.PRODUCT_ID = FP.PRODUCT_ID
where YEAR(PRODUCE_DATE) = 2022 and MONTH(PRODUCE_DATE) = 5
GROUP BY FO.PRODUCT_ID
order by sum(AMOUNT)*FP.PRICE desc, FO.PRODUCT_ID