-- 코드를 입력하세요
SELECT Ai.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI join ANIMAL_OUTS AO on AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE like "Intact%" and (AO.SEX_UPON_OUTCOME like "Spayed%" or AO.SEX_UPON_OUTCOME like "Neutered%")
ORDER BY AI.ANIMAL_ID