-- 코드를 입력하세요
SELECT PD.PRODUCT_CODE, sum(PD.PRICE*OS.SALES_AMOUNT) as SALES
FROM OFFLINE_SALE OS left join PRODUCT PD on OS.PRODUCT_ID = PD.PRODUCT_ID
GROUP BY OS.PRODUCT_ID
ORDER BY SALES desc, PRODUCT_CODE