WITH discount AS (
 SELECT
  CAR_TYPE, DISCOUNT_RATE
 FROM
  CAR_RENTAL_COMPANY_DISCOUNT_PLAN
 WHERE
  DURATION_TYPE LIKE '30%')

SELECT
 car.CAR_ID, car.CAR_TYPE, TRUNCATE(car.DAILY_FEE * (1-discount.DISCOUNT_RATE*0.01) * 30, 0) AS FEE
FROM
 CAR_RENTAL_COMPANY_CAR car
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY history ON car.CAR_ID = history.CAR_ID
JOIN discount ON car.CAR_TYPE = discount.CAR_TYPE
WHERE
 car.CAR_ID NOT IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE '2022-11-01' BETWEEN START_DATE AND END_DATE
                     OR
                     '2022-11-30' BETWEEN START_DATE AND END_DATE
                     OR
                     (START_DATE >= '2022-11-01' AND END_DATE <= '2022-11-30'))
 AND
 car.CAR_TYPE IN ('세단', 'SUV')
GROUP BY
 CAR_ID
HAVING
 FEE BETWEEN 500000 AND 2000000
ORDER BY
 FEE DESC, car.CAR_TYPE, car.CAR_ID DESC;