-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) as YEAR, MONTH(OS.SALES_DATE) as MONTH, GENDER, count( DISTINCT OS.USER_ID) as USERS
FROM ONLINE_SALE OS INNER JOIN  USER_INFO UI on OS.USER_ID = UI.USER_ID
WHERE UI.GENDER is not null
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER