SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F, (
    SELECT CATEGORY, MAX(PRICE) AS MPRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) M
WHERE F.CATEGORY = M.CATEGORY AND F.PRICE = M.MPRICE
ORDER BY MAX_PRICE DESC;