-- 코드를 입력하세요
WITH RECURSIVE TEMP AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TEMP
    WHERE HOUR < 23
)

SELECT HOUR, COUNT(ANIMAL_OUTS.DATETIME)
FROM TEMP
LEFT OUTER JOIN ANIMAL_OUTS
ON HOUR(ANIMAL_OUTS.DATETIME) = TEMP.HOUR
GROUP BY HOUR;