-- 코드를 입력하세요
SELECT AP.APNT_NO,	PT.PT_NAME,	PT.PT_NO,	AP.MCDP_CD,	DR.DR_NAME,	AP.APNT_YMD
FROM (APPOINTMENT AP join PATIENT PT on AP.PT_NO = PT.PT_NO ) join DOCTOR DR on AP.MDDR_ID = DR.DR_ID
WHERE DATE_FORMAT(AP.APNT_YMD, "%Y-%m-%d") = "2022-04-13" and APNT_CNCL_YN = "N"
ORDER BY APNT_YMD