-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(avg(R.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO as I inner join REST_REVIEW as R on I.REST_ID = R.REST_ID
GROUP BY R.REST_ID
HAVING I.ADDRESS like '서울%'
ORDER BY ROUND(avg(R.REVIEW_SCORE), 3) DESC, I.FAVORITES DESC